### ISSUE TITLE
1 урок. исправления

### ISSUE THREAD

**Issue by emptyb** [anniege/anniege.github.io#1]
Не пропорциональный отступ между ФИО и фото. 
лучше указывать в каждом элементе где есть текст font-size, font-family и line-height. т.к. в дальнейшем будут большие сайты, где обычно подключен не один шрифт. 
В font-family через запятую нужно еще дописать serif или sans-serif
можно прописывал отступ слева для текста с помощью padding-left вместо text-indent.

**Comment by anniege** [comment]
fixed

**Comment by emptyb** [comment]
wrapper высоту тут ненадо указывать
Фио написано в теге h3. переделаййте тегом h1
все теги div должны быть с классом. допишите их. это не корректно. в больших проектах будет тяжело потом что-либо наити или исправить
