### ISSUE TITLE
3 дз

### ISSUE THREAD

**Issue by emptyb** [anniege/anniege.github.io#2]
body  background:#fff; - он и так белый изначально. нет необходимости лишний раз прописывать
.logo- указана и ширина и высота. в данном случае можно не указывать. лучше указать нижний падинг, а не маргин
menu_list и menu_list_item классы можно не задавать.
ul: font-size:0px... еще нужно line-height и vertical-align по 0px
.menu_list_item  border-right: 1px solid #999; -- нужно задать бордеры через ховер
когда задаются элементам float:right/left у родителя должен быть прописан класс clearfix. почитайте и доделайте,
bicycle     line-height: 398px;  может все же падингами? =)
.content p  указаны и высота и ширина... а если текста будет больше? по высоте не влезет... тем более прописан overflow:hiden; текст будет просто сьедаться
в меню и футере прописано (О_Нас) орф ошибка

**Comment by anniege** [comment]
Исправлено

**Comment by emptyb** [comment]
Напишите О_Нас без нижнего подчеркивания
bicycle заданы такие падинги, что text-aligh не работает=) вместо падингов можно указать ширину блока

Зачет

**Comment by emptyb** [comment]
в бонусе прописаны opacity:1 это стандартое своиство. его не надо указывать. при ховере затемняются надписи под имг. нужно сделать чтобы opacity было только на имг. лучше те же имг вырезать с рамками, а не позиционировать те рамки.

**Comment by anniege** [comment]
Спасибо за замечания! Исправлено.
