### ISSUE TITLE
6

### ISSUE THREAD

**Issue by emptyb** [anniege/anniege.github.io#5]
все select под меню поползли. разной высоты и стрелки смещены.
fieldset бренды (справо) расположены не как на макете.
footer_logos- отступ справо лучше задать для li а не для а. чтобы между ссылками были промежутки. так понятней на границах куда нажимаешь.

**Comment by anniege** [comment]
footer_logos исправлено

**Comment by emptyb** [comment]
https://gyazo.com/fa92e65e51ba96aba957a27f155c8a22
разные отступы между селектами. нет левого отступа внутри селекта.
