### ISSUE TITLE
exam (7-9)

### ISSUE THREAD

**Issue by emptyb** [anniege/anniege.github.io#8]
есть недочеты по мелочам
ширина от 768пх - .brands имеет по бокам отступы меньше, чем у блоков снизу
https://monosnap.com/file/VG8uCBRS3gRlD1j54ZqvuDeQx0R9Pb

**Comment by anniege** [comment]
поправила

**Comment by emptyb** [comment]
https://monosnap.com/file/KIwfyiUQphRTx39zy5CX66x87WWOWO
https://monosnap.com/file/lnCVGf8aKcGvCdZ5vuXkKBWXCWMGF8
https://monosnap.com/file/1NH5IegdW3m2Cg4IkLL6v2FTmSubLi
https://monosnap.com/file/ntOGU3fEm7Jl2EETqxDHkkp2tAGAQD

**Comment by emptyb** [comment]
done
